blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("blogs/archive/<str:year>/<str:month>/", views.blog_archive_view, name='blog_archive_view'),
    path("blogs/category/<slug:category_slug>/", views.blog_category_view, name='blog_category_view'),
    path("blogs/tag/<slug:tag_slug>/", views.blog_tag_view, name='blog_tag_view'),
    path("blogs/search/", views.blog_search_view, name='blog_search_view'),
    path("blogs/", views.blog_list_view, name="blog_list_view"),
    path("blog/<slug:blog_slug>/", views.blog_detail_view, name="blog_detail_view"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace="core")),
    path("", include('account.urls', namespace="account")),
    path("", include('product.urls', namespace="product")),
    path("", include('blog.urls', namespace="blog")),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from core.models import AbstractModel
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.


class BlogCategory(AbstractModel):
    name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(verbose_name="Active", default=True)
    slug = AutoSlugField(populate_from="name", unique=True)

    class Meta:
        verbose_name = "Blog Category"
        verbose_name_plural = "Blog Categories"

    def __str__(self):
        return self.name


class BlogTag(AbstractModel):
    name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(verbose_name="Active", default=True)
    slug = AutoSlugField(populate_from="name", unique=True)

    class Meta:
        verbose_name = "Blog Tag"
        verbose_name_plural = "Blog Tags"

    def __str__(self):
        return self.name


class Blog(AbstractModel):
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="blogs")
    blog_categories = models.ManyToManyField(
        BlogCategory, related_name="blogs")
    blog_tags = models.ManyToManyField(BlogTag, related_name="blogs")

    title = models.CharField(max_length=250)
    content = RichTextField()
    cover_image = models.ImageField(
        upload_to="blog_cover_images", default="blog_cover_images/default_blog_cover.jpg")
    publish_date = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(verbose_name="Active", default=True)
    slug = AutoSlugField(populate_from="title", unique=True)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"

    def __str__(self):
        return f"{self.title} - ({self.author})"


class BlogReview(AbstractModel):
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name="reviews")
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name="blog_reviews")

    full_name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=100)
    comment = models.TextField()

    class Meta:
        verbose_name = "Blog Review"
        verbose_name_plural = "Blog Reviews"

    def __str__(self):
        if self.user:
            user_identifier = self.user.get_username()
        else:
            user_identifier = self.full_name

        if self.parent:
            return f"{self.subject} - {user_identifier} ~~ (Parent: {self.parent})"
        else:
            return f"{self.subject} - {user_identifier}"

blog/forms.py
from django import forms
from .models import BlogReview


class BlogReviewAdminForm(forms.ModelForm):
    class Meta:
        model = BlogReview
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get("instance")

        if instance:
            if BlogReview.objects.filter(parent=instance).exists():
                self.fields["blog"].disabled = True

    def is_recursive_parent(self, parent, target):
        if parent is None:
            return False
        elif parent == target:
            return True
        else:
            return self.is_recursive_parent(parent.parent, target)

    def clean_parent(self):
        parent = self.cleaned_data.get('parent')
        if parent == self.instance:
            raise forms.ValidationError("A comment cannot be its own parent.")
        elif parent and self.is_recursive_parent(parent, self.instance):
            raise forms.ValidationError(
                "This comment cannot be a parent of its own parent.")
        return parent

    def clean(self):
        cleaned_data = super().clean()
        user = cleaned_data.get('user')
        full_name = cleaned_data.get('full_name')
        email = cleaned_data.get('email')

        if user:
            if full_name or email:
                if full_name:
                    self.add_error('full_name', forms.ValidationError(
                        "Full name field should be empty when user is specified.", code='invalid_full_name'))
                if email:
                    self.add_error('email', forms.ValidationError(
                        "Email field should be empty when user is specified.", code='invalid_email'))
        else:
            if not full_name:
                self.add_error('full_name', forms.ValidationError(
                    "Full name field is required when user is not specified.", code='required_full_name'))
            if not email:
                self.add_error('email', forms.ValidationError(
                    "Email field is required when user is not specified.", code='required_email'))

blog/views.py
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.urls import reverse_lazy
from .models import Blog, BlogCategory, BlogTag


# Create your views here.


def blog_list_view(request):
    blogs = Blog.objects.filter(is_active=True).order_by("-publish_date")
    blogs_count = blogs.count()

    paginator = Paginator(blogs, 6)
    page = request.GET.get('page')
    try:
        page_number = int(page)
    except TypeError:
        page_number = 1
    except ValueError:
        raise Http404("Invalid page number.")

    try:
        blogs = paginator.page(page_number)
    except EmptyPage:
        raise Http404("Invalid page number.")

    context = {
        "blogs": blogs,
        "blogs_count": blogs_count,
    }
    return render(request, "blog/blog-list.html", context)


def blog_detail_view(request, blog_slug):
    blog = get_object_or_404(Blog, slug=blog_slug, is_active=True)

    related_blogs = Blog.objects.filter(
        Q(blog_categories__in=blog.blog_categories.all()) & ~Q(id=blog.id)).distinct()[:3]

    if "recently_viewed" in request.session:
        if blog.id in request.session["recently_viewed"]:
            request.session["recently_viewed"].remove(blog.id)

        request.session["recently_viewed"].insert(0, blog.id)
        if len(request.session["recently_viewed"]) > 5:
            request.session["recently_viewed"].pop()
    else:
        request.session["recently_viewed"] = [blog.id]
    request.session.modified = True

    context = {
        "blog": blog,
        "related_blogs": related_blogs,
    }
    return render(request, "blog/blog-detail.html", context)


def blog_archive_view(request, year, month):
    month = month.lower()

    try:
        blog_date = datetime.strptime(f"{year}/{month}", "%Y/%B")
    except ValueError:
        raise Http404("Invalid date format.")

    blogs = Blog.objects.filter(is_active=True, publish_date__year=year,
                                publish_date__month=blog_date.month).order_by("-publish_date")
    blogs_count = blogs.count()

    paginator = Paginator(blogs, 6)
    page = request.GET.get('page')
    try:
        page_number = int(page)
    except TypeError:
        page_number = 1
    except ValueError:
        raise Http404("Invalid page number.")

    try:
        blogs = paginator.page(page_number)
    except EmptyPage:
        raise Http404("Invalid page number.")

    context = {
        "blogs": blogs,
        "blogs_count": blogs_count,
    }
    return render(request, "blog/blog-list.html", context)


def blog_category_view(request, category_slug):
    category = get_object_or_404(
        BlogCategory, slug=category_slug, is_active=True)
    blogs = Blog.objects.filter(
        is_active=True, blog_categories__slug=category_slug).order_by("-publish_date")
    blogs_count = blogs.count()

    paginator = Paginator(blogs, 6)
    page = request.GET.get('page')
    try:
        page_number = int(page)
    except TypeError:
        page_number = 1
    except ValueError:
        raise Http404("Invalid page number.")

    try:
        blogs = paginator.page(page_number)
    except EmptyPage:
        raise Http404("Invalid page number.")

    context = {
        "blogs": blogs,
        "category": category,
        "blogs_count": blogs_count,
    }
    return render(request, "blog/blog-list.html", context)


def blog_tag_view(request, tag_slug):
    tag = get_object_or_404(BlogTag, slug=tag_slug, is_active=True)
    blogs = Blog.objects.filter(
        is_active=True, blog_tags__slug=tag_slug).order_by("-publish_date")
    blogs_count = blogs.count()

    paginator = Paginator(blogs, 6)
    page = request.GET.get('page')
    try:
        page_number = int(page)
    except TypeError:
        page_number = 1
    except ValueError:
        raise Http404("Invalid page number.")

    try:
        blogs = paginator.page(page_number)
    except EmptyPage:
        raise Http404("Invalid page number.")

    context = {
        "blogs": blogs,
        "tag": tag,
        "blogs_count": blogs_count,
    }
    return render(request, "blog/blog-list.html", context)


def blog_search_view(request):
    query = request.GET.get('query')

    if not query:
        return redirect(reverse_lazy("blog:blog_list_view"))
    else:
        blogs = Blog.objects.filter(
            title__icontains=query, is_active=True).order_by("-publish_date")
        blogs_count = blogs.count()

        paginator = Paginator(blogs, 6)
        page = request.GET.get('page')
        try:
            page_number = int(page)
        except TypeError:
            page_number = 1
        except ValueError:
            raise Http404("Invalid page number.")

        try:
            blogs = paginator.page(page_number)
        except EmptyPage:
            raise Http404("Invalid page number.")

        context = {
            "blogs": blogs,
            "query": query,
            "blogs_count": blogs_count,
        }
        return render(request, "blog/blog-list.html", context)

blog/templates/blog/blog-detail.html
{% extends 'core/base.html' %}
{% load static tags %}


{% block page_title %}
  <title>PAVSHOP - Multipurpose eCommerce HTML5 Template</title>
{% endblock page_title %}


{% block main %}
  <!--======= SUB BANNER =========-->
  {% include "core/includes/sub-banner.html" %}
  
  <!-- Content -->
  <div id="content"> 
    
    <!-- Blog List -->
    <section class="blog-list blog-list-3 single-post padding-top-100 padding-bottom-100">
      <div class="container">
        <div class="row">
          <div class="col-md-9"> 
            
            <!-- Article -->
            <article> 
              <!-- Post Img --> 
              <img class="img-responsive" src="{{ blog.cover_image.url }}" alt="" > 
              <!-- Tittle -->
              <div class="post-tittle left"> <a href="#." class="tittle">{{ blog.title }}</a> 
                <!-- Post Info --> 
                <span><i class="primary-color icon-user"></i> by {{ blog.author.get_username }}</span> 
                <span><i class="primary-color icon-calendar"></i> {{ blog.publish_date|date:"F d, Y H:i" }}</span> 
                <span><i class="primary-color icon-bubble"></i> {{ blog.reviews.count }}</span> 
                <span><i class="primary-color icon-tag"></i>
                  {% for category in blog.blog_categories.all %}
                    {% if category.is_active %}
                    <a href="{% url 'blog:blog_category_view' category.slug %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                    {% endif %}
                  {% endfor %}
                </span>
              </div>
              <!-- Post Content -->
              <div class="text-left">
                {{ blog.content|safe }}
                
                <!-- Tags -->
                <div class="row margin-top-50">
                  <div class="col-md-8">
                    <h5 class="shop-tittle">BLOG TAGS</h5>
                    <ul class="shop-tags padding-left-15">
                      {% for tag in blog.blog_tags.all %}
                        {% if tag.is_active %}
                          <li><a href="{% url 'blog:blog_tag_view' tag.slug %}">{{ tag.name }}</a></li>
                        {% endif %}
                      {% endfor %}
                    </ul>
                  </div>
                  
                  <!-- Share With -->
                  <div class="col-md-4">
                    <h5 class="shop-tittle">share with</h5>
                    <ul class="share-post">
                      <li><a href="#."><i class="icon-social-facebook"></i> Facebook</a></li>
                      <li><a href="#."><i class="icon-social-twitter"></i> twitter</a></li>
                    </ul>
                  </div>
                </div>
                
                <!-- ADMIN info -->
                <div class="admin-info">
                  <div class="media-left">
                    <div class="admin-pic"> <img class="img-fluid" style="max-width: 100%;" src="{{ blog.author.profile_image.url }}" alt=""> </div>
                  </div>
                  <div class="media-body">
                    <h6>{{ blog.author.first_name }} {{ blog.author.last_name|slice:"1" }}. <span>{{ blog.author.position.name }}</span></h6>
                    <p>
                      {{ blog.author.bio }}
                    </p>
                    <div class="admin-social"> 
                      <a href="#."><i class="icon-social-facebook"></i></a> 
                      <a href="#."><i class="icon-social-twitter"></i></a> 
                      <a href="#."><i class="icon-social-dribbble"></i></a> 
                      <a href="#."><i class="icon-envelope"></i></a> 
                    </div>
                  </div>
                </div>
                
                <!--=======  COMMENTS =========-->
                <div class="comments margin-top-80">
                  <h5 class="shop-tittle margin-bottom-30">COMMENTS</h5>
                  <ul class="media-list padding-left-15">
                    <!--=======  COMMENTS =========-->
                    <li class="media">
                      <div class="media-left"> <a href="#" class="avatar"> <img class="media-object img-responsive" src="{% static 'images/avatar-1.jpg' %}" alt=""> <br>
                        </a> </div>
                      <div class="media-body">
                        <h6 class="media-heading">William Saron <span><i class="icon-clock primary-color"></i> April 27, 2016 - 10:00 am</span></h6>
                        <p>Crack commando unit was sent to prison by a military court for a crime they didn't commit. ese men promptly escaped from a maximum security stockade to the Los Angeles. </p>
                        <a href="#." class="raply"><i class="icon-bubble primary-color"></i> Reply</a> </div>
                    </li>
                    <!--=======  COMMENTS =========-->
                    <li class="media">
                      <div class="media-left"> <a href="#" class="avatar"> <img class="media-object img-responsive" src="{% static 'images/avatar-3.jpg' %}" alt=""> <br>
                        </a> </div>
                      <div class="media-body">
                        <h6 class="media-heading">William Saron <span><i class="icon-clock primary-color"></i> April 27, 2016 - 10:00 am</span></h6>
                        <p>Crack commando unit was sent to prison by a military court for a crime they didn't commit. ese men promptly escaped from a maximum security stockade to the Los Angeles. </p>
                        <a href="#." class="raply"><i class="icon-bubble primary-color"></i> Reply</a> </div>
                    </li>
                    <!--=======  COMMENTS =========-->
                    <li class="media padding-left-100">
                      <div class="media-left"> <a href="#" class="avatar"> <img class="media-object img-responsive" src="{% static 'images/avatar-2.jpg' %}" alt=""> <br>
                        </a> </div>
                      <div class="media-body">
                        <h6 class="media-heading">William Saron <span><i class="icon-clock primary-color"></i> April 27, 2016 - 10:00 am</span></h6>
                        <p>Crack commando unit was sent to prison by a military court for a crime they didn't commit. ese men promptly escaped from a maximum security stockade to the Los Angeles. </p>
                        <a href="#." class="raply"><i class="icon-bubble primary-color"></i> Reply</a> </div>
                    </li>
                    <!--=======  COMMENTS =========-->
                    <li class="media">
                      <div class="media-left"> <a href="#" class="avatar"> <img class="media-object img-responsive" src="{% static 'images/avatar-3.jpg' %}" alt=""> <br>
                        </a> </div>
                      <div class="media-body">
                        <h6 class="media-heading">William Saron <span><i class="icon-clock primary-color"></i> April 27, 2016 - 10:00 am</span></h6>
                        <p>Crack commando unit was sent to prison by a military court for a crime they didn't commit. ese men promptly escaped from a maximum security stockade to the Los Angeles. </p>
                        <a href="#." class="raply"><i class="icon-bubble primary-color"></i> Reply</a> </div>
                    </li>
                  </ul>
                  <hr>
                  
                  <!--=======  LEAVE COMMENTS =========-->
                  <h5 class="shop-tittle margin-top-80">POST YOUR COMMENTS</h5>
                  <form class="padding-left-15">
                    <ul class="row">
                      <li class="col-sm-4">
                        <label>Name
                          <input type="text" class="form-control" name="name" placeholder="">
                        </label>
                      </li>
                      <li class="col-sm-4">
                        <label>Email
                          <input type="text" class="form-control" name="name" placeholder="">
                        </label>
                      </li>
                      <li class="col-sm-4">
                        <label>Subject
                          <input type="text" class="form-control" name="name" placeholder="">
                        </label>
                      </li>
                      <li class="col-sm-12">
                        <label>COMMENTS
                          <textarea class="form-control" placeholder=""></textarea>
                        </label>
                      </li>
                      <li class="col-sm-12">
                        <button type="submit" class="btn margin-top-30">Submit Comment </button>
                      </li>
                    </ul>
                  </form>
                </div>
              </div>
            </article>
            <hr>
            
            <!--  You May Like -->
            <h5 class="shop-tittle margin-top-50 margin-bottom-50">you may like </h5>
            <div class="alos-like padding-left-15"> 
              {% for related_blog in related_blogs %}
                <!-- Article -->
                <article>
                  <div class="row">
                    <div class="col-sm-5"> 
                      <!-- Post Img --> 
                      <img class="img-responsive" src="{{ related_blog.cover_image.url }}" alt="" > </div>
                    <div class="col-sm-7"> 
                      <!-- Tittle -->
                      <div class="post-tittle left"> <a href="{% url 'blog:blog_detail_view' related_blog.slug %}" class="tittle">{{ related_blog.title }}</a> 
                        <!-- Post Info --> 
                        <span><i class="primary-color icon-user"></i> by {{ related_blog.author.get_username }}</span> 
                        <span><i class="primary-color icon-calendar"></i> {{ related_blog.publish_date|date:"F d, Y H:i" }}</span> 
                        <span><i class="primary-color icon-bubble"></i> {{ related_blog.reviews.count }}</span> 
                        <span><i class="primary-color icon-tag"></i>
                          {% for category in related_blog.blog_categories.all %}
                          {% if category.is_active %}
                            <a href="{% url 'blog:blog_category_view' category.slug %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                          {% endif %}
                          {% endfor %}
                        </span> 
                      </div>
                      <!-- Post Content -->
                      <div class="text-left">
                        <p>
                          {{ related_blog.content|striptags|truncatechars:200|safe }}
                        </p>
                        <a href="{% url 'blog:blog_detail_view' related_blog.slug %}" class="red-more">READ MORE</a> </div>
                    </div>
                  </div>
                </article>
              {% endfor %}
            </div>
          </div>

          <!-- Sider Bar -->
          <div class="col-md-3">
            <div class="shop-sidebar"> 
              
              <!-- SEARCH -->
              {% include "blog/includes/blog-search.html" %}
              
              <!-- Category -->
              {% include "blog/includes/blog-categories.html" %}

              <!-- Recent Post -->
              {% get_recently_viewed_blogs %}
              
              <!-- TAGS -->
              {% get_blog_popular_tags %}

              
              <!-- ARCHIVES -->
              {% get_previous_months %}
              
              <!-- SIDE BAR BANER -->
              <div class="side-bnr margin-top-50"> <img class="img-responsive" src="{% static 'images/sidebar-bnr.jpg' %}" alt="">
                <div class="position-center-center"> <span class="price"><small>$</small>299</span>
                  <div class="bnr-text">look
                    hot
                    with
                    style</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- Culture BLOCK -->
    <section class="cultur-block">
      <ul>
        <li> <img src="{% static 'images/cultur-img-1.jpg' %}" alt="" > </li>
        <li> <img src="{% static 'images/cultur-img-2.jpg' %}" alt="" > </li>
        <li> <img src="{% static 'images/cultur-img-3.jpg' %}" alt="" > </li>
        <li> <img src="{% static 'images/cultur-img-4.jpg' %}" alt="" > </li>
      </ul>
      
      <!-- Culture Text -->
      <div class="position-center-center">
        <div class="container">
          <div class="col-sm-6 center-block">
            <h4>FOLLOW US @ INSTAGRAM</h4>
            <p>Phasellus lacinia fermentutm bibendum. Interdum et malante ipuctus non. Nulla lacinia,
              eros vel fermentum consectetur, ris dolor in ex. </p>
          </div>
        </div>
      </div>
    </section>
    
    <!-- News Letter -->
    {% include "core/includes/news-letter.html" %}
  </div>
{% endblock main %}