account/urls.py
from django.urls import path, re_path
from . import views
 
app_name = "account"
urlpatterns = [
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),
    path('register/', views.register_view, name="register_view"),
    path('load-cities/', views.load_cities_view, name='load_cities_view'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})/$', views.activate_view, name='activate_view'),
    path('request-new-token/', views.request_new_token_view, name='request_new_token_view'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("blogs/archive/<str:year>/<str:month>/", views.blog_archive_view, name='blog_archive_view'),
    path("blogs/category/<slug:category_slug>/", views.blog_category_view, name='blog_category_view'),
    path("blogs/tag/<slug:tag_slug>/", views.blog_tag_view, name='blog_tag_view'),
    path("blogs/search/", views.blog_search_view, name='blog_search_view'),
    path("blogs/", views.blog_list_view, name="blog_list_view"),
    path("blog/<slug:blog_slug>/", views.blog_detail_view, name="blog_detail_view"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls', namespace="core")),
    path("", include('account.urls', namespace="account")),
    path("", include('product.urls', namespace="product")),
    path("", include('blog.urls', namespace="blog")),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path('', views.index_view, name="index_view"),
    path('shopping-cart/', views.shopping_cart_view, name="shopping_cart_view"),
    path('wishlist/', views.wishlist_view, name="wishlist_view"),
    path('contact/', views.contact_view, name="contact_view"),
    path('checkout/', views.checkout_view, name="checkout_view"),
    path('about-us/', views.about_us_view, name="about_us_view"),
]

core/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.


class AbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Contact(AbstractModel):
    full_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=50)
    phone_number = PhoneNumberField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

    def __str__(self):
        return f"{self.subject} - {self.full_name}"


class Newsletter(AbstractModel):
    email = models.EmailField(max_length=50, unique=True)
    subscription_status = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Newsletter"
        verbose_name_plural = "Newsletters"

    def __str__(self):
        return self.email

core/forms.py
from django import forms
from .models import Contact
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class ContactForm(forms.ModelForm):
    phone_number = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(attrs={'class': 'form-control'}))

    class Meta:
        model = Contact
        fields = (
            "full_name",
            "email",
            "phone_number",
            "subject",
            "message",
        )
        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
            'subject': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import ContactForm


# Create your views here.


def index_view(request):
    return render(request, "core/index.html")


def shopping_cart_view(request):
    return render(request, "core/shopping-cart.html")


@login_required
def wishlist_view(request):
    return render(request, "core/wishlist.html")


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Thank You. Your message has been sent successfully!")
            return redirect(reverse_lazy("core:contact_view"))
        else:
            messages.error(
                request, "Oops! Something went wrong. Please review your message and make sure all the required fields are filled correctly.")
    else:
        form = ContactForm()

    context = {
        "form": form,
    }
    return render(request, "core/contact.html", context)


def checkout_view(request):
    return render(request, "core/checkout.html")


def about_us_view(request):
    return render(request, "core/about-us.html")

core/templates/core/includes/about.html
<section class="small-about padding-top-150 padding-bottom-150">
  <div class="container"> 
    
    <!-- Main Heading -->
    <div class="heading text-center">
      <h4>about PAVSHOP</h4>
      <p>Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia,
        eros vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in ex. </p>
    </div>
    
    <!-- Social Icons -->
    <ul class="social_icons">
      <li><a href="#."><i class="icon-social-facebook"></i></a></li>
      <li><a href="#."><i class="icon-social-twitter"></i></a></li>
      <li><a href="#."><i class="icon-social-tumblr"></i></a></li>
      <li><a href="#."><i class="icon-social-youtube"></i></a></li>
      <li><a href="#."><i class="icon-social-dribbble"></i></a></li>
    </ul>
  </div>
</section>

core/templates/core/includes/alert-close-message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissable text-center">
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissable text-center">
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissable text-center">
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissable text-center">
        {% else %}
            <div class="alert alert-dismissable text-center">
        {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{{ message }}</strong>
            </div>
    {% endfor %}
{% endif %}

core/templates/core/includes/alert-message.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success">
        {% elif message.tags == 'info' %}
            <div class="alert alert-info">
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning">
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger">
        {% else %}
            <div class="alert">
        {% endif %}
                <strong>{{ message }}</strong>
            </div>
    {% endfor %}
{% endif %}

core/templates/core/includes/footer.html
{% load static %}

<footer>
  <div class="container"> 
    
    <!-- Location -->
    <div class="col-md-3">
      <div class="about-footer"> <img class="margin-bottom-30" src="{% static 'images/logo-foot.png' %}" alt="" >
        <p><i class="icon-pointer"></i> Street No. 12, Newyork 12, <br>   MD - 123, USA.</p>
        <p><i class="icon-call-end"></i> 1.800.123.456789</p>
        <p><i class="icon-envelope"></i> info@PAVSHOP.com</p>
      </div>
    </div>
    
    <!-- HELPFUL LINKS -->
    <div class="col-md-3">
      <h6>HELPFUL LINKS</h6>
      <ul class="link">
        <li><a href="#."> Products</a></li>
        <li><a href="#."> Find a Store</a></li>
        <li><a href="#."> Features</a></li>
        <li><a href="#."> Privacy Policy</a></li>
        <li><a href="#."> Blog</a></li>
        <li><a href="#."> Press Kit </a></li>
      </ul>
    </div>
    
    <!-- SHOP -->
    <div class="col-md-3">
      <h6>SHOP</h6>
      <ul class="link">
        <li><a href="#."> About Us</a></li>
        <li><a href="#."> Career</a></li>
        <li><a href="#."> Shipping Methods</a></li>
        <li><a href="#."> Contact</a></li>
        <li><a href="#."> Support</a></li>
        <li><a href="#."> Retailer</a></li>
      </ul>
    </div>
    
    <!-- MY ACCOUNT -->
    <div class="col-md-3">
      <h6>MY ACCOUNT</h6>
      <ul class="link">
        <li><a href="#."> Login</a></li>
        <li><a href="#."> My Account</a></li>
        <li><a href="#."> My Cart</a></li>
        <li><a href="#."> Wishlist</a></li>
        <li><a href="#."> Checkout</a></li>
      </ul>
    </div>
    
    <!-- Rights -->
    <div class="rights">
      <p>©  2017 PAVSHOP All right reserved. </p>
      <div class="scroll"> <a href="#wrap" class="go-up"><i class="lnr lnr-arrow-up"></i></a> </div>
    </div>
  </div>
</footer>  

core/templates/core/includes/header.html
{% load static %}

<header>
  <div class="sticky">
    <div class="container"> 
      
      <!-- Logo -->
      <div class="logo"> <a href="{% url 'core:index_view' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}" alt="" ></a> </div>
      <nav class="navbar ownmenu">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-open-btn" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"><i class="fa fa-navicon"></i></span> </button>
        </div>
        
         <!-- NAV -->
        <div class="collapse navbar-collapse" id="nav-open-btn">
          <ul class="nav">
            <li class="{% if request.resolver_match.view_name == 'core:index_view' %}active{% endif %}"> <a href="{% url 'core:index_view' %}">Home</a> </li>
            <li class="{% if request.resolver_match.view_name == 'blog:blog_list_view' %}active{% endif %}"> <a href="{% url 'blog:blog_list_view' %}" >Blog</a> </li>
            
            <!-- Two Link Option -->
            <li class="dropdown"> <a href="#." class="dropdown-toggle" data-toggle="dropdown">Designer</a>
              <div class="dropdown-menu two-option">
                <div class="row">
                  <ul class="col-sm-6">
                    <li> <a href="#">summer store</a></li>
                    <li> <a href="#"> sarees</a></li>
                    <li> <a href="#"> kurtas</a></li>
                    <li> <a href="#"> shorts & tshirts</a></li>
                    <li> <a href="#"> winter wear</a></li>
                    <li> <a href="#"> jeans</a></li>
                    <li> <a href="#"> bra</a></li>
                    <li> <a href="#"> babydools</a> </li>
                  </ul>
                  <ul class="col-sm-6">
                    <li> <a href="#">deodornts</a></li>
                    <li> <a href="#"> skin care</a></li>
                    <li> <a href="#"> make up</a></li>
                    <li> <a href="#"> watch</a></li>
                    <li> <a href="#"> siting bags</a></li>
                    <li> <a href="#"> totes</a></li>
                    <li> <a href="#"> gold rings</a></li>
                    <li> <a href="#"> jewellery</a></li>
                  </ul>
                </div>
              </div>
            </li>
            
            <!-- MEGA MENU -->
            <li class="dropdown megamenu {% if request.resolver_match.view_name == 'product:product_list_view' %}active{% endif %}"> 
              <a href="{% url 'product:product_list_view' %}" class="dropdown-toggle">store</a>
              <div class="dropdown-menu">
                <div class="row"> 
                  
                  <!-- Top Rate Products -->
                  <div class="col-md-7">
                    <h6>Top Rate Products</h6>
                    <div class="top-rated">
                      <ul>
                        <li>
                          <div class="media-left">
                            <div class="cart-img"> <a href="#"> <img class="media-object img-responsive" src="{% static 'images/cart-img-1.jpg' %}" alt="..."> </a> </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading">WOOD CHAIR</h6>
                            <div class="stars"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                            <span class="price">129.00 USD</span> </div>
                        </li>
                        <li>
                          <div class="media-left">
                            <div class="cart-img"> <a href="#"> <img class="media-object img-responsive" src="{% static 'images/cart-img-2.jpg' %}" alt="..."> </a> </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading">STOOL</h6>
                            <div class="stars"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                            <span class="price">129.00 USD</span> </div>
                        </li>
                        <li>
                          <div class="media-left">
                            <div class="cart-img"> <a href="#"> <img class="media-object img-responsive" src="{% static 'images/cart-img-3.jpg' %}" alt="..."> </a> </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading">WOOD SPOON</h6>
                            <div class="stars"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                            <span class="price">129.00 USD</span> </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                  
                  <!-- New Arrival -->
                  <div class="col-md-5">
                    <h5>NEW ARRIVAL 2016 <span>(Best Collection)</span></h5>
                    <img class="nav-img" src="{% static 'images/nav-img.png' %}" alt="" >
                    <p>Lorem ipsum dolor sit amet,<br>
                      consectetur adipiscing elit. <br>
                      Donec faucibus maximus<br>
                      vehicula.</p>
                    <a href="#." class="btn btn-small btn-round">SHOP NOW</a> </div>
                </div>
              </div>
            </li>
            <li class="{% if request.resolver_match.view_name == 'core:about_us_view' %}active{% endif %}"> 
              <a href="{% url 'core:about_us_view' %}">About </a> 
            </li>
            <li class="{% if request.resolver_match.view_name == 'core:contact_view' %}active{% endif %}"> 
              <a href="{% url 'core:contact_view' %}"> contact</a> 
            </li>
          </ul>
        </div>
        
        <!-- Nav Right -->
        <div class="nav-right">
          <ul class="navbar-right">
            
            <!-- USER INFO -->
            {% if request.user.is_authenticated %}
              <li class="dropdown user-acc"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" ><i class="icon-user"></i> </a>
                <ul class="dropdown-menu">
                  <li>
                    <h6>HELLO! {{ request.user.get_full_name }}</h6>
                  </li>
                  <li><a href="{% url 'core:wishlist_view' %}">FAVORITES</a></li>
                  <li><a href="#">ACCOUNT INFO</a></li>
                  <li><a href="{% url 'account:logout_view' %}">LOG OUT</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{% url 'account:login_view' %}"><i class="fa fa-sign-in"></i></a></li>
              <li><a href="{% url 'account:register_view' %}"><i class="fa fa-user-plus"></i></a></li>  
            {% endif %}

            <!-- USER BASKET -->
            <li class="dropdown user-basket"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="icon-basket-loaded"></i> </a>
              <ul class="dropdown-menu">
                <li>
                  <div class="media-left">
                    <div class="cart-img"> <a href="#"> <img class="media-object img-responsive" src="{% static 'images/cart-img-1.jpg' %}" alt="..."> </a> </div>
                  </div>
                  <div class="media-body">
                    <h6 class="media-heading">WOOD CHAIR</h6>
                    <span class="price">129.00 USD</span> <span class="qty">QTY: 01</span> </div>
                </li>
                <li>
                  <div class="media-left">
                    <div class="cart-img"> <a href="#"> <img class="media-object img-responsive" src="{% static 'images/cart-img-2.jpg' %}" alt="..."> </a> </div>
                  </div>
                  <div class="media-body">
                    <h6 class="media-heading">WOOD STOOL</h6>
                    <span class="price">129.00 USD</span> <span class="qty">QTY: 01</span> </div>
                </li>
                <li>
                  <h5 class="text-center">SUBTOTAL: 258.00 USD</h5>
                </li>
                <li class="margin-0">
                  <div class="row">
                    <div class="col-xs-6"> <a href="{% url 'core:shopping_cart_view' %}" class="btn">VIEW CART</a></div>
                    <div class="col-xs-6 "> <a href="{% url 'core:checkout_view' %}" class="btn">CHECK OUT</a></div>
                  </div>
                </li>
              </ul>
            </li>
            
            <!-- SEARCH BAR -->
            <li class="dropdown"> <a href="javascript:void(0);" class="search-open"><i class=" icon-magnifier"></i></a>
              <div class="search-inside animated bounceInUp"> <i class="icon-close search-close"></i>
                <div class="search-overlay"></div>
                <div class="position-center-center">
                  <div class="search">
                    <form>
                      <input type="search" placeholder="Search Shop">
                      <button type="submit"><i class="icon-check"></i></button>
                    </form>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>

core/templates/core/includes/home-main-slider.html
{% load static %}

<section class="home-slider"> 
  
    <!-- SLIDE Start -->
    <div class="tp-banner-container">
      <div class="tp-banner">
        <ul>
          <!-- SLIDE  -->
          <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" > 
            <!-- MAIN IMAGE --> 
            <img src="{% static 'images/slide-bg-1.jpg' %}"  alt="slider"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"> 
            <!-- LAYERS --> 
            <!-- LAYER NR. 1 -->
            <div class="tp-caption font-playfair sfb tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="-200" 
                data-speed="800" 
                data-start="500" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 7; font-size:18px; color:#fff; max-width: auto; max-height: auto; white-space: nowrap;">The Latest Product from PAVSHOP</div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfl font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="-120" 
                data-speed="800" 
                data-start="800" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:80px; color:#2d3a4b; text-transform:uppercase; white-space: nowrap;"><small class="font-regular">$</small>299 </div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="0" 
                data-speed="800" 
                data-start="800" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:120px; color:#fff; text-transform:uppercase; white-space: nowrap;">featured </div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="110" 
                data-speed="800" 
                data-start="1300" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:120px; color:#fff; text-transform:uppercase; white-space: nowrap;">cycle </div>
            <!-- LAYER NR. 4 -->
            <div class="tp-caption lfb tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="240" 
                data-speed="800" 
                data-start="2200" 
                data-easing="Power3.easeInOut" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                data-scrolloffset="0"
                style="z-index: 8;"><a href="#." class="btn">SHOP NOW</a> </div>
          </li>
          
          <!-- SLIDE  -->
          <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" > 
            <!-- MAIN IMAGE --> 
            <img src="{% static 'images/slide-bg-2.jpg'%}"  alt="slider"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat"> 
            <!-- LAYERS --> 
            <!-- LAYER NR. 1 -->
            <div class="tp-caption font-playfair sfb tp-resizeme" 
                data-x="center" data-hoffset="0" 
                data-y="center" data-voffset="-150" 
                data-speed="800" 
                data-start="500" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 7; font-size:18px; color:#fff; max-width: auto; max-height: auto; white-space: nowrap;">The Latest Product from PAVSHOP</div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-regular tp-resizeme letter-space-4" 
                data-x="center" data-hoffset="0" 
                data-y="center" data-voffset="-50" 
                data-speed="800" 
                data-start="800" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:78px; color:#fff; text-transform:uppercase; white-space: nowrap;">look beautiful </div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-extra-bold tp-resizeme letter-space-4" 
                data-x="center" data-hoffset="0" 
                data-y="center" data-voffset="60" 
                data-speed="800" 
                data-start="1300" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:140px; color:#fff; text-transform:uppercase; white-space: nowrap;">this season </div>
            <!-- LAYER NR. 4 -->
            <div class="tp-caption sfb font-extra-bold tp-resizeme" 
                data-x="center" data-hoffset="120"
                data-y="center" data-voffset="200"
                data-speed="800" 
                data-start="2200" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:60px; color:#fff; text-transform:uppercase; white-space: nowrap;"><small class="font-regular">$</small> 299 </div>
            <!-- LAYER NR. 4 -->
            <div class="tp-caption lfb tp-scrollbelowslider tp-resizeme" 
                data-x="center" data-hoffset="-120" 
                data-y="center" data-voffset="200" 
                data-speed="800" 
                data-start="2200" 
                data-easing="Power3.easeInOut" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                data-scrolloffset="0"
                style="z-index: 8;"><a href="#." class="btn">BUY NOW</a> </div>
          </li>
        </ul>
      </div>
    </div>
  </section>

core/templates/core/includes/news-letter.html
<section class="news-letter padding-top-150 padding-bottom-150">
  <div class="container">
    <div class="heading light-head text-center margin-bottom-30">
      <h4>NEWSLETTER</h4>
      <span
        >Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac
        ante ipsumien lacus, eu posuere odi
      </span>
    </div>
    <form>
      <input type="email" placeholder="Enter your email address" required />
      <button type="submit">SEND ME</button>
    </form>
  </div>
</section>

core/templates/core/includes/sub-banner.html
<section class="sub-bnr" data-stellar-background-ratio="0.5">
  <div class="position-center-center">
    <div class="container">
      <h4>contact us now</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus
        maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam
      </p>
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">contact</li>
      </ol>
    </div>
  </div>
</section>